name: 🚀 Deploy Website to YMC

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Running Deployment Process
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server:  ftp.oxford.pss
          # server: ftp.oxford.ps
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          server-dir: /public_html/
          # server-dir: /public_html/demo/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/storage/*.key
            .env
            .env.example
            phpunit.xml
            README.md
            docker-compose.yml
            docker-compose.override.yml
            .editorconfig
            .styleci.yml
